services:

  mdbook:
    command: mdbook watch
    build: .
    volumes:
      - ./home/:/home
      - ./src/:/home/src
      - ./docs/:/home/book
    working_dir: /home

  troff:
    command: bash
    build: ./troff
    volumes:
      - ./home/:/home
      - ./src/:/home/src
    working_dir: /home